### ISSUE TITLE
大佬求解决awa

### ISSUE THREAD

**Issue by Marea-qq** [aicezam/SmartOnmyoji#2]
[ WARN:0@0.512] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\img\yuhun\end_fail.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 73, in <module>
    main()
  File "C:\Users\DJS\AppData\Local\Programs\Python\Python39\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 54, in main
    start_click(args.connect_mod, args.modname, args.hwd_title, args.click_deviation, args.interval_seconds,
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleStart.py", line 65, in start_click
    target_info = GetTargetPicInfo(modname, compress_val=1).get_target_info  # 目标图片不压缩（本身就小）
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleGetTargetInfo.py", line 80, in get_target_info
    img_hw[i] = img.shape[:2]  # 获取目标图片宽高
AttributeError: 'NoneType' object has no attribute 'shape'
目标图片读取中……
[ WARN:0@0.543] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\img\huodong\end_fail.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 73, in <module>
    main()
  File "C:\Users\DJS\AppData\Local\Programs\Python\Python39\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 54, in main
    start_click(args.connect_mod, args.modname, args.hwd_title, args.click_deviation, args.interval_seconds,
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleStart.py", line 65, in start_click
    target_info = GetTargetPicInfo(modname, compress_val=1).get_target_info  # 目标图片不压缩（本身就小）
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleGetTargetInfo.py", line 80, in get_target_info
    img_hw[i] = img.shape[:2]  # 获取目标图片宽高
AttributeError: 'NoneType' object has no attribute 'shape'
目标图片读取中……
[ WARN:0@0.398] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\img\huodong\end_fail.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 73, in <module>
    main()
  File "C:\Users\DJS\AppData\Local\Programs\Python\Python39\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 54, in main
    start_click(args.connect_mod, args.modname, args.hwd_title, args.click_deviation, args.interval_seconds,
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleStart.py", line 65, in start_click
    target_info = GetTargetPicInfo(modname, compress_val=1).get_target_info  # 目标图片不压缩（本身就小）
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleGetTargetInfo.py", line 80, in get_target_info
    img_hw[i] = img.shape[:2]  # 获取目标图片宽高
AttributeError: 'NoneType' object has no attribute 'shape'
目标图片读取中……
[ WARN:0@0.375] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\img\huodong\end_fail.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 73, in <module>
    main()
  File "C:\Users\DJS\AppData\Local\Programs\Python\Python39\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 54, in main
    start_click(args.connect_mod, args.modname, args.hwd_title, args.click_deviation, args.interval_seconds,
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleStart.py", line 65, in start_click
    target_info = GetTargetPicInfo(modname, compress_val=1).get_target_info  # 目标图片不压缩（本身就小）
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleGetTargetInfo.py", line 80, in get_target_info
    img_hw[i] = img.shape[:2]  # 获取目标图片宽高
AttributeError: 'NoneType' object has no attribute 'shape'
目标图片读取中……
[ WARN:0@0.376] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\img\yuhun\end_fail.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 73, in <module>
    main()
  File "C:\Users\DJS\AppData\Local\Programs\Python\Python39\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\smart_onmyoji_start.py", line 54, in main
    start_click(args.connect_mod, args.modname, args.hwd_title, args.click_deviation, args.interval_seconds,
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleStart.py", line 65, in start_click
    target_info = GetTargetPicInfo(modname, compress_val=1).get_target_info  # 目标图片不压缩（本身就小）
  File "C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\modules\ModuleGetTargetInfo.py", line 80, in get_target_info
    img_hw[i] = img.shape[:2]  # 获取目标图片宽高
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by aicezam** [comment]
`imread_('C:\Users\DJS\OneDrive\桌面\GG\yys\python\SmartOnmyoji-main\img\yuhun\end_fail.jpg'): can't open/read file: check file path/integrity`
@Marea-qq 
额，突然想起来，opencv读取图片的时候，不支持路径里面有中文，可以把项目文件夹放其他地方，改天优化一下，读取图片的那个方法可以改成这个：

```
def cv_imread(filepath):
    cv_img = cv2.imdecode(np.fromfile(filepath, dtype=np.uint8), -1)
    return cv_img
```

**Comment by Marea-qq** [comment]
好的，多谢大佬了。

**Comment by aicezam** [comment]
已修复
