### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by xinbim** [aicezam/SmartOnmyoji#5]
![bug](https://user-images.githubusercontent.com/77722762/159840114-ea8f953c-823c-44bf-a71c-72dcf79d7f23.png)

**Comment by aicezam** [comment]
https://cloud.tencent.com/developer/article/1702622
https://stackoverflow.com/questions/53131954/modulenotfounderror-no-module-named-windows

是依赖库没装好，这个pymouse有点问题

**Comment by aicezam** [comment]
https://cloud.tencent.com/developer/article/1702622
https://stackoverflow.com/questions/53131954/modulenotfounderror-no-module-named-windows

是依赖库没装好，这个pymouse有点问题

**Comment by xinbim** [comment]
谢谢  问题解决了

**Comment by xinbim** [comment]
又出问题了 

目标图片读取中……
读取完成！共[ 12 ]张图片
['end_fail.jpg', 'end_win_0.jpg', 'end_win_1.jpg', 'end_win_2.jpg', 'end_win_3.jpg', 'hun11_start.jpg', 'hun11_start1.jpg', 'hun11_start_zhunbei.jpg', 'hun_rukou1.jpg', 'hun_rukou2.jpg', 'hun_rukou3.jpg', 'queren.jpg']
Traceback (most recent call last):
  File "F:\YYS\python\files\SmartOnmyoji-main\smart_onmyoji_start.py", line 79, in <module>
    main()
  File "C:\Users\xinbi\AppData\Local\Programs\Python\Python37\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "F:\YYS\python\files\SmartOnmyoji-main\smart_onmyoji_start.py", line 61, in main
    args.loop_min, args.compress_val, args.match_method, args.scr_and_click_method)
  File "F:\YYS\python\files\SmartOnmyoji-main\modules\ModuleStart.py", line 86, in start_click
    handle_set.set_priority(randint(3, 5))  # 设置目标程序优先级，避免程序闪退
  File "F:\YYS\python\files\SmartOnmyoji-main\modules\ModuleHandleSet.py", line 84, in set_priority
    handle = OpenProcess(PROCESS_ALL_ACCESS, True, pid)
pywintypes.error: (5, 'OpenProcess', '拒绝访问。')
目标图片读取中……
读取完成！共[ 12 ]张图片
['end_fail.jpg', 'end_win_0.jpg', 'end_win_1.jpg', 'end_win_2.jpg', 'end_win_3.jpg', 'hun11_start.jpg', 'hun11_start1.jpg', 'hun11_start_zhunbei.jpg', 'hun_rukou1.jpg', 'hun_rukou2.jpg', 'hun_rukou3.jpg', 'queren.jpg']
Traceback (most recent call last):
  File "F:\YYS\python\files\SmartOnmyoji-main\smart_onmyoji_start.py", line 79, in <module>
    main()
  File "C:\Users\xinbi\AppData\Local\Programs\Python\Python37\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "F:\YYS\python\files\SmartOnmyoji-main\smart_onmyoji_start.py", line 61, in main
    args.loop_min, args.compress_val, args.match_method, args.scr_and_click_method)
  File "F:\YYS\python\files\SmartOnmyoji-main\modules\ModuleStart.py", line 86, in start_click
    handle_set.set_priority(randint(3, 5))  # 设置目标程序优先级，避免程序闪退
  File "F:\YYS\python\files\SmartOnmyoji-main\modules\ModuleHandleSet.py", line 84, in set_priority
    handle = OpenProcess(PROCESS_ALL_ACCESS, True, pid)
pywintypes.error: (5, 'OpenProcess', '拒绝访问。')
目标图片读取中……
读取完成！共[ 12 ]张图片
['end_fail.jpg', 'end_win_0.jpg', 'end_win_1.jpg', 'end_win_2.jpg', 'end_win_3.jpg', 'hun11_start.jpg', 'hun11_start1.jpg', 'hun11_start_zhunbei.jpg', 'hun_rukou1.jpg', 'hun_rukou2.jpg', 'hun_rukou3.jpg', 'queren.jpg']
Traceback (most recent call last):
  File "F:\YYS\python\files\SmartOnmyoji-main\smart_onmyoji_start.py", line 79, in <module>
    main()
  File "C:\Users\xinbi\AppData\Local\Programs\Python\Python37\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "F:\YYS\python\files\SmartOnmyoji-main\smart_onmyoji_start.py", line 61, in main
    args.loop_min, args.compress_val, args.match_method, args.scr_and_click_method)
  File "F:\YYS\python\files\SmartOnmyoji-main\modules\ModuleStart.py", line 86, in start_click
    handle_set.set_priority(randint(3, 5))  # 设置目标程序优先级，避免程序闪退
  File "F:\YYS\python\files\SmartOnmyoji-main\modules\ModuleHandleSet.py", line 84, in set_priority
    handle = OpenProcess(PROCESS_ALL_ACCESS, True, pid)
pywintypes.error: (5, 'OpenProcess', '拒绝访问。')

**Comment by aicezam** [comment]
使用【管理员】身份运行cmd或者power shell呢？

**Comment by xinbim** [comment]
也是不行的

**Comment by aicezam** [comment]
更新了一下，拉最新的代码试试

**Comment by xinbim** [comment]
拉了新代码 可以正常运行了  pygui可以识别但是 不会点击 ，尝试过管理员运行 cmd shell 都不可以点击  这个原因困扰我很久了  之前用一个大佬的程（链接 https://github.com/lisai9093/YYS）也不行，他的程序我是通过把py文件用pyinstaller编译成exe运行后解决的这个问题  ，然后我就尝试了同样的方法 ，编译为exe文件后 （如图
![bug](https://user-images.githubusercontent.com/77722762/160221176-f65b6979-c6e5-4d34-928f-0e2087e009e3.png)
）

**Comment by aicezam** [comment]
在我俩电脑运行的好好的，这个程序编译成exe后会有地址读取不到的bug，还没有找到办法解决😂
另外，可能是因为脚本程序的进程优先级没有游戏窗体的高，所以没法点点击，可以试试手动打开任务管理器，右键点击脚本的进程，设置一下优先级

**Comment by aicezam** [comment]
打包用这个
`pyinstaller -D smart_onmyoji_start.py -w`
然后打包完后，把img文件夹放到生成后的程序目录下面，跟 smart_onmyoji_start.exe 同一个目录就行了

**Comment by xinbim** [comment]
设置了优先级 还是不行  我去试试你刚发我的这个  我之前打包用的是这个
PS G:\python> pyinstaller -F F:\YYS\python\files\SmartOnmyoji-main11\smart_onmyoji_start.py

**Comment by xinbim** [comment]
好了！！！完美解决！！！谢谢大大  期待百鬼程序
